import { v4 as uuidv4 } from 'uuid';

export const MOCK_MOVIES = [
  {
    id: uuidv4(),
    imageURL:
      'https://upload.wikimedia.org/wikipedia/en/a/a2/Star_Wars_The_Force_Awakens_Theatrical_Poster.jpg',
    title: 'Star Wars: Episode VII - The Force Awakens',
    summary:
      'As a new threat to the galaxy rises, Rey, a desert scavenger, and Finn, an ex-stormtrooper, must join Han Solo and Chewbacca to search for the one hope of restoring peace.',
    rating: 7.9,
    genre: 'Action, Adventure, Sci-Fi',
    releaseDate: '2015-12-18',
    duration: 138,
    popularity: 9500,
    cast: ['Daisy Ridley', 'John Boyega', 'Harrison Ford'],
    director: 'J.J. Abrams',
    budget: 245000000,
    revenue: 2068223624,
    language: 'English',
    country: 'United States',
    ratings: {
      imdb: 7.9,
      rottenTomatoes: 85,
      metacritic: 81,
    },
    isClassic: false,
    type: 'Sequel',
    platforms: ['Disney+', 'Amazon Prime'],
    reviews: [
      {
        user: 'JohnDoe',
        comment: 'Amazing movie with stunning visuals!',
        rating: 9,
      },
      {
        user: 'JaneSmith',
        comment: 'Great for fans, but lacks originality.',
        rating: 7,
      },
    ],
  },
  {
    id: uuidv4(),
    imageURL:
      'https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg',
    title: 'Avengers: Endgame',
    summary:
      'After the devastating events of Avengers: Infinity War, the Avengers assemble once more to reverse Thanos’ actions and restore balance to the universe.',
    rating: 8.4,
    genre: 'Action, Sci-Fi',
    releaseDate: '2019-04-26',
    duration: 181,
    popularity: 10000,
    cast: ['Robert Downey Jr.', 'Chris Evans', 'Scarlett Johansson'],
    director: 'Anthony Russo, Joe Russo',
    budget: 356000000,
    revenue: 2797800564,
    language: 'English',
    country: 'United States',
    ratings: {
      imdb: 8.4,
      rottenTomatoes: 94,
      metacritic: 78,
    },
    isClassic: false,
    type: 'Sequel',
    platforms: ['Disney+', 'Apple TV+'],
    reviews: [
      {
        user: 'MarvelFan',
        comment: 'An epic conclusion to a decade-long journey!',
        rating: 10,
      },
      {
        user: 'MovieCritic',
        comment: 'Great action, but too much fan service.',
        rating: 7,
      },
    ],
  },
  {
    id: uuidv4(),
    imageURL:
      'https://upload.wikimedia.org/wikipedia/en/e/ed/Toy_Story_4_poster.jpg',
    title: 'Toy Story 4',
    summary:
      'When a new toy named Forky joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy.',
    rating: 7.8,
    genre: 'Animation, Adventure, Comedy',
    releaseDate: '2019-06-21',
    duration: 100,
    popularity: 8700,
    cast: ['Tom Hanks', 'Tim Allen', 'Annie Potts'],
    director: 'Josh Cooley',
    budget: 200000000,
    revenue: 1073394593,
    language: 'English',
    country: 'United States',
    ratings: {
      imdb: 7.8,
      rottenTomatoes: 97,
      metacritic: 84,
    },
    isClassic: false,
    type: 'Sequel',
    platforms: ['Disney+', 'HBO Max'],
    reviews: [
      {
        user: 'FamilyLover',
        comment: 'A heartwarming adventure for all ages!',
        rating: 9,
      },
      {
        user: 'CriticalThinker',
        comment: 'Not as impactful as the previous movies.',
        rating: 6,
      },
    ],
  },
  {
    id: uuidv4(),
    imageURL:
      'https://upload.wikimedia.org/wikipedia/en/6/69/Black_Panther_film_poster.jpg',
    title: 'Black Panther',
    summary:
      'T’Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country’s past.',
    rating: 7.3,
    genre: 'Action, Adventure, Sci-Fi',
    releaseDate: '2018-02-16',
    duration: 134,
    popularity: 9800,
    cast: ['Chadwick Boseman', 'Michael B. Jordan', 'Lupita Nyong’o'],
    director: 'Ryan Coogler',
    budget: 200000000,
    revenue: 1346913161,
    language: 'English',
    country: 'United States',
    ratings: {
      imdb: 7.3,
      rottenTomatoes: 96,
      metacritic: 88,
    },
    isClassic: false,
    type: 'Original',
    platforms: ['Disney+'],
    reviews: [
      {
        user: 'SuperheroFan',
        comment: 'A revolutionary movie for the superhero genre!',
        rating: 10,
      },
      {
        user: 'FilmBuff',
        comment: 'Good, but the hype overshadowed its flaws.',
        rating: 8,
      },
    ],
  },
  {
    id: uuidv4(),
    imageURL:
      'https://upload.wikimedia.org/wikipedia/en/8/8a/Inception_%282010%29_theatrical_poster.jpg',
    title: 'Inception',
    summary:
      'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
    rating: 8.8,
    genre: 'Action, Adventure, Sci-Fi',
    releaseDate: '2010-07-16',
    duration: 148,
    popularity: 10200,
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page'],
    director: 'Christopher Nolan',
    budget: 160000000,
    revenue: 829895144,
    language: 'English',
    country: 'United States',
    ratings: {
      imdb: 8.8,
      rottenTomatoes: 91,
      metacritic: 74,
    },
    isClassic: false,
    type: 'Original',
    platforms: ['Netflix', 'Amazon Prime'],
    reviews: [
      {
        user: 'DreamLover',
        comment: 'A mind-bending masterpiece!',
        rating: 10,
      },
      {
        user: 'CriticPro',
        comment: 'Compelling story, but overly complex at times.',
        rating: 8,
      },
    ],
  },
  {
    id: uuidv4(),
    imageURL:
      'https://upload.wikimedia.org/wikipedia/en/5/50/Interstellar_film_poster.jpg',
    title: 'Interstellar',
    summary:
      'A team of explorers travel through a wormhole in space in an attempt to ensure humanity’s survival.',
    rating: 8.6,
    genre: 'Adventure, Drama, Sci-Fi',
    releaseDate: '2014-11-07',
    duration: 169,
    popularity: 10800,
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    director: 'Christopher Nolan',
    budget: 165000000,
    revenue: 701729206,
    language: 'English',
    country: 'United States',
    ratings: {
      imdb: 8.6,
      rottenTomatoes: 72,
      metacritic: 74,
    },
    isClassic: false,
    type: 'Original',
    platforms: ['HBO Max', 'Amazon Prime'],
    reviews: [
      {
        user: 'SpaceLover',
        comment: 'An emotional journey through space and time!',
        rating: 10,
      },
      {
        user: 'ScienceBuff',
        comment: 'Beautiful visuals, but scientifically flawed.',
        rating: 7,
      },
    ],
  },
  {
    id: uuidv4(),
    imageURL:
      'https://upload.wikimedia.org/wikipedia/en/a/a9/The_Dark_Knight_%282008_film%29_poster.jpg',
    title: 'The Dark Knight',
    summary:
      'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.',
    rating: 9.0,
    genre: 'Action, Crime, Drama',
    releaseDate: '2008-07-18',
    duration: 152,
    popularity: 11200,
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    director: 'Christopher Nolan',
    budget: 185000000,
    revenue: 1004558444,
    language: 'English',
    country: 'United States',
    ratings: {
      imdb: 9.0,
      rottenTomatoes: 94,
      metacritic: 84,
    },
    isClassic: false,
    type: 'Sequel',
    platforms: ['HBO Max', 'Amazon Prime'],
    reviews: [
      {
        user: 'BatFan',
        comment: 'Heath Ledger’s Joker is iconic!',
        rating: 10,
      },
      {
        user: 'CinemaPro',
        comment: 'Best superhero movie ever made!',
        rating: 10,
      },
    ],
  },
  {
    id: uuidv4(),
    imageURL:
      'https://upload.wikimedia.org/wikipedia/en/7/7a/The_Shawshank_Redemption.jpg',
    title: 'The Shawshank Redemption',
    summary:
      'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    rating: 9.3,
    genre: 'Drama',
    releaseDate: '1994-09-22',
    duration: 142,
    popularity: 13000,
    cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'],
    director: 'Frank Darabont',
    budget: 25000000,
    revenue: 28800000,
    language: 'English',
    country: 'United States',
    ratings: {
      imdb: 9.3,
      rottenTomatoes: 91,
      metacritic: 80,
    },
    isClassic: true,
    type: 'Original',
    platforms: ['Netflix', 'Amazon Prime'],
    reviews: [
      {
        user: 'ClassicFan',
        comment: 'A timeless masterpiece about hope.',
        rating: 10,
      },
      {
        user: 'CriticX',
        comment: 'The ultimate feel-good movie.',
        rating: 10,
      },
    ],
  },
  {
    id: uuidv4(),
    imageURL:
      'https://upload.wikimedia.org/wikipedia/en/c/c3/Titanic_poster.jpg',
    title: 'Titanic',
    summary:
      'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
    rating: 7.8,
    genre: 'Drama, Romance',
    releaseDate: '1997-12-19',
    duration: 195,
    popularity: 15000,
    cast: ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane'],
    director: 'James Cameron',
    budget: 200000000,
    revenue: 2187463944,
    language: 'English',
    country: 'United States',
    ratings: {
      imdb: 7.8,
      rottenTomatoes: 89,
      metacritic: 75,
    },
    isClassic: true,
    type: 'Original',
    platforms: ['Disney+', 'HBO Max'],
    reviews: [
      {
        user: 'RomanceLover',
        comment: 'A heartbreaking love story on a legendary ship.',
        rating: 9,
      },
      {
        user: 'HistoryBuff',
        comment: 'Visually stunning but overly sentimental.',
        rating: 7,
      },
    ],
  },
  {
    id: uuidv4(),
    imageURL:
      'https://upload.wikimedia.org/wikipedia/en/9/95/Forrest_Gump_poster.jpg',
    title: 'Forrest Gump',
    summary:
      'The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.',
    rating: 8.8,
    genre: 'Drama, Romance',
    releaseDate: '1994-07-06',
    duration: 142,
    popularity: 14000,
    cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
    director: 'Robert Zemeckis',
    budget: 55000000,
    revenue: 678200000,
    language: 'English',
    country: 'United States',
    ratings: {
      imdb: 8.8,
      rottenTomatoes: 70,
      metacritic: 82,
    },
    isClassic: true,
    type: 'Original',
    platforms: ['Netflix', 'Amazon Prime'],
    reviews: [
      {
        user: 'LifeFan',
        comment: 'Life is like a box of chocolates!',
        rating: 10,
      },
      {
        user: 'CriticPro',
        comment: 'Inspirational but slightly overhyped.',
        rating: 8,
      },
    ],
  },
  {
    id: uuidv4(),
    imageURL:
      'https://upload.wikimedia.org/wikipedia/en/1/19/The_Lion_King_poster.jpg',
    title: 'The Lion King',
    summary:
      'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
    rating: 8.5,
    genre: 'Animation, Adventure, Drama',
    releaseDate: '1994-06-24',
    duration: 88,
    popularity: 12000,
    cast: ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones'],
    director: 'Roger Allers, Rob Minkoff',
    budget: 45000000,
    revenue: 968500000,
    language: 'English',
    country: 'United States',
    ratings: {
      imdb: 8.5,
      rottenTomatoes: 93,
      metacritic: 88,
    },
    isClassic: true,
    type: 'Original',
    platforms: ['Disney+'],
    reviews: [
      {
        user: 'FamilyLover',
        comment: 'A touching tale of love, loss, and redemption.',
        rating: 10,
      },
      {
        user: 'CriticX',
        comment: 'Timeless music and a powerful story.',
        rating: 9,
      },
    ],
  },
  {
    id: uuidv4(),
    imageURL:
      'https://upload.wikimedia.org/wikipedia/en/a/a5/La_La_Land_%28film%29.png',
    title: 'La La Land',
    summary:
      'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
    rating: 8.0,
    genre: 'Comedy, Drama, Music',
    releaseDate: '2016-12-09',
    duration: 128,
    popularity: 11000,
    cast: ['Ryan Gosling', 'Emma Stone', 'John Legend'],
    director: 'Damien Chazelle',
    budget: 30000000,
    revenue: 448900000,
    language: 'English',
    country: 'United States',
    ratings: {
      imdb: 8.0,
      rottenTomatoes: 91,
      metacritic: 93,
    },
    isClassic: false,
    type: 'Original',
    platforms: ['Netflix', 'Amazon Prime'],
    reviews: [
      {
        user: 'MusicFan',
        comment: 'A magical blend of music and romance.',
        rating: 9,
      },
      {
        user: 'CriticalThinker',
        comment: 'Visually stunning but a bit clichéd.',
        rating: 7,
      },
    ],
  },
];
